apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: additional-scrape-configs
type: Opaque
stringData:
  prometheus-additional.yaml: |-
    - job_name: node-exporter
      ec2_sd_configs:
        - region: ap-southeast-1
          port: 9100
          access_key: <access key>
          secret_key: <secret key>
          filters:
            - name: tag:node-exporter
              values:
                - true
      relabel_configs:
        - source_labels: [__meta_ec2_instance_id]
          target_label: instance_id
        - source_labels: [__meta_ec2_tag_Name]
          target_label: instance
        - regex: "__meta_ec2_tag_(.+)"
          action: labelmap
